version: "2"

services:
  web:
    build: .
    ports:
      - "80:80"
    container_name: phppr_web
    volumes:
      - "./src/themes:/var/www/html/wp-content/themes"
      - "./src/plugins:/var/www/html/wp-content/plugins"
    links:
      - mysqldb:mysqldb
    environment:
      PHP_SITE_NAME: dev

  mysqldb:
    image: mysql/mysql-server
    container_name: phppr_mysqldb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./docker-runtime/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phppr_phpmyadmin
    environment:
      PMA_HOST: mysqldb
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    restart: always
    ports:
      - 8001:80
    volumes:
      - ./docker-runtime/sessions:/sessions
